pipeline {
    agent any
    stages {
        stage('Run API Tests') {
            steps {
                bat 'mvn clean test'
            }
        }
    }
    post {
        always {
            publishHTML(target: [
                reportDir: 'reports',
                reportFiles: 'cucumber-report.html',
                reportName: 'API Automation Report'
            ])
        }
    }
}
